ALTER TABLE "Order"
  ADD COLUMN "originLat" DOUBLE PRECISION,
  ADD COLUMN "originLng" DOUBLE PRECISION,
  ADD COLUMN "destinationLat" DOUBLE PRECISION,
  ADD COLUMN "destinationLng" DOUBLE PRECISION;
